export const POSTS = {
    GET_POSTS: "POSTS.GET_POSTS",
    GET_POSTS_SUCCESS: "POSTS.GET_POSTS_SUCCESS",
    GET_POSTS_ERROR: "POSTS.GET_POSTS_ERROR",
    GET_POPULAR_POSTS: "POSTS.GET_POPULAR_POSTS",
    GET_POPULAR_POSTS_SUCCESS: "POSTS.GET_POPULAR_POSTS_SUCCESS",
    GET_POPULAR_POSTS_ERROR: "POSTS.GET_POPULAR_POSTS_ERROR",
    GET_LATEST_POSTS: "POSTS.GET_LATEST_POSTS",
    GET_LATEST_POSTS_SUCCESS: "POSTS.GET_LATEST_POSTS_SUCCESS",
    GET_LATEST_POSTS_ERROR: "POSTS.GET_LATEST_POSTS_ERROR",
};
