export const APPLICATION = {
    GET_USER: 'APPLICATION.GET_USER',
    GET_USER_SUCCESS: 'APPLICATION.GET_USER_SUCCESS',
    GET_USER_ERROR: 'APPLICATION.GET_USER_ERROR',
    GET_CATEGORIES: 'APPLICATION.GET_CATEGORIES',
    GET_CATEGORIES_SUCCESS: 'APPLICATION.GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_ERROR: 'APPLICATION.GET_CATEGORIES_ERROR',
}